### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by altinnadmin** [Altinn/altinn-infoportal#2]
Currently this PoC is using github pages. We should instead use a proper solution for hosting.

### Tasks

- [ ] Migrate to using [Static Web Apps](https://azure.microsoft.com/en-us/services/app-service/static/) for hosting and GitHub Actions for build/deploy.

**Comment by andreasbalevik** [comment]
Need to add a oauth service for Netlify CMS login. 
https://www.netlifycms.org/docs/github-backend/ (if we want to use github for authentication)

For localhost, we use a default oauth provider hosted at Netlify. This does not work in production.

example config:

```
backend:
  name: github
  # Replace this with the GitHub repo you want to make change
  repo: github-username/target-github-repo
  # This site_domain and base_url are placeholders, replace with the correct one.
  site_domain: https://some-cms-domain.com # CMS's domain
  base_url: https://some-oauth-domain.com # OAuth Server's domain
```
