### ISSUE TITLE
Need to add a oauth service for Netlify CMS login.

### ISSUE THREAD

**Issue by andreasbalevik** [Altinn/altinn-infoportal#60]
Need to add a oauth service for Netlify CMS login. 
https://www.netlifycms.org/docs/github-backend/ (if we want to use github for authentication)

example config:

```
backend:
  name: github
  # Replace this with the GitHub repo you want to make change
  repo: github-username/target-github-repo
  # This site_domain and base_url are placeholders, replace with the correct one.
  site_domain: https://some-cms-domain.com # CMS's domain
  base_url: https://some-oauth-domain.com # OAuth Server's domain
```

For localhost, the default oauth provider is hosted by Netlify. This does not work in production.

https://infoportal.no/admin/#/ does not work...

- [ ] setup a dedicated oauth server for github authentication in Netlify CMS

_Originally posted by @andreasbalevik in https://github.com/Altinn/altinn-infoportal/issues/2#issuecomment-1054131403_
